### ISSUE TITLE
removeSync causing infinite loop on certain objects

### ISSUE THREAD

**Issue by drschwabe** [joaopmi/circular-reference-remover#1]
Am using this to remove circular references that caused an infinite loop while sending back/forth an object over socket.io connection.   That was a delight to fix automagically and not have to manually edit objects. 

However, while I found removeSync works in most cases,  in others I have found the function can also itself trigger an infinite loop. 

I am tentatively/lazily debugging this at the moment so might be able to pinpoint specifically the shape of the object that is causing removeSync to infiloop but was just wondering if maintainer or anyone else has had this occur and if perhaps we can arrange a fix.   In my mind, this lib should be bulletproof against infinte loops.

**Comment by joaopmi** [comment]
Hello friend, how are you?
About the loop, can you provide me some example or parameter that you are using?
